### ISSUE TITLE
Console error : An invalid form control with name='store_state' is not focusable.

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#496] opened 2019-08-29 12:08 UTC
When going through the onboarding wizard on the ecom plan, I can't get past the first screen:

https://cloudup.com/c91k8X_JVyM

Looking in the console this is the error I see:

https://cloudup.com/cd-m6q1Oic2

**Comment by psealock** [comment] 2019-08-30 00:10
I'm not able to reproduce locally. Is this an Atomic test site? Do you have a url?

**Comment by warrendholmes** [comment] 2019-08-30 06:47
It seems like my province (or state) wasn't passed through correctly for South Africa. I managed to get through by editing my address. 

We should either:

- Pre-validate the form 
- Just populate the fields but leave them editable

**Comment by pmcpinto** [comment] 2020-06-04 09:54
I'm going to close this issue, as we're going to implement the new obw that we have on Core.

**Closed by pmcpinto** 2020-06-04 09:54 UTC
Labels: eCommerce Plan
