### ISSUE TITLE
Help header and modal in WooCommerce setup screen gets cut off

### ISSUE THREAD

**Issue by coreymckrill** [Automattic/wc-calypso-bridge#782] opened 2022-04-06 22:50 UTC
I encountered this while working on setting up a test site on Atomic:

![Screen Shot 2022-04-05 at 14 44 50](https://user-images.githubusercontent.com/916023/162084978-c5cf78bb-adb4-4df3-9e79-05498f287bd1.png)

Using the latest Firefox.

This happened when I started setting up WooPay, left the screen, and then came back to it (maybe I left twice?). Refreshing the screen fixed the layout so I was able to see the entire modal and click the "Got it" button.

More discussion of the issue here: p1649195426060399-slack-C3ECCGUVC

**Comment by moon0326** [comment] 2022-06-16 20:54
Closing it for now as we've been unable to reproduce the issue. Please feel free to re-open it if needed.

**Closed by moon0326** 2022-06-16 20:54 UTC
