### ISSUE TITLE
Navigation: Feature toggle is shown twice when wc-admin is installed

### ISSUE THREAD

**Issue by elizaan36** [Automattic/wc-calypso-bridge#747] opened 2021-09-09 19:02 UTC
In Ecom plan stores, when wc-admin is installed, there are two checkboxes appearing to enable or disable the new nav.
<img width="1690" alt="Screen Shot 2021-09-02 at 2 43 13 PM" src="https://user-images.githubusercontent.com/5121465/132746717-f88765ee-23bb-4922-91ea-fcd30bfa85cf.png">

It's required to uncheck both to disable the navigation, then the nav disappears altogether. A refresh will bring back the unified nav but it's quite disorienting.
<img width="1261" alt="Screen Shot 2021-09-09 at 1 51 58 PM" src="https://user-images.githubusercontent.com/5121465/132746676-8d11d8cd-6f24-47ab-87f2-41c2562e190d.png">

There should only be one checkbox to enable/disable the new nav, and the transition to the WPCOM nav shouldn't require a manual refresh.

**Comment by mattsherman** [comment] 2021-09-16 18:25
@elizaan36 I cannot reproduce this with a new eComm site. Can you let me know what version of WooCommerce you are seeing this with, and if WooCommerce Admin is also installed as a standalone plugin?

**Comment by elizaan36** [comment] 2021-09-16 20:37
Thanks for looking into this. Here's the plugin info:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/5121465/133682400-782526b3-41e3-41f8-ac4d-109580663970.png">

WooCommerce 5.6 and WCA 2.6.2

**Comment by mattsherman** [comment] 2021-09-17 19:40
@elizaan36 Thanks! I can reproduce this. It occurs when wc-admin is installed as a standalone plugin.

@pmcpinto What should be the priority of addressing this?

**Comment by pmcpinto** [comment] 2021-09-20 10:03
This feels like an edge case, but I'll add it to the backlog of the upcoming cycle.

**Comment by mattsherman** [comment] 2021-11-03 14:13
I mistakenly kept myself assigned to this after grooming. Removing myself, as I am not actively working on it.

**Comment by mattsherman** [comment] 2021-11-22 23:42
@joelclimbsthings What is the status on this one?

**Comment by joelclimbsthings** [comment] 2021-11-22 23:51
@mattsherman I was still trying to reproduce in my dev environment, but put it off during the cool-down. Not sure of the priority, but my intention was to revisit with the coming sprint.

**Comment by mattsherman** [comment] 2021-11-23 01:13
Thanks. I'll move it back to the Cycle Backlog, at the bottom of the pipeline, priority-wise. It is an edge case that, while annoying, is not really harmful. I'll also un-assign you for now, since you are not actively working on it.

**Closed** 2021-12-21 15:46 UTC
Labels: bug, Navigation
