### ISSUE TITLE
MailChimp_Settings_Controller Warning when WooCommerce plugin is disabled.

### ISSUE THREAD

**Issue by budzanowski** [Automattic/wc-calypso-bridge#13] opened 2017-11-27 15:59 UTC
### Information

User has observed following issue when WooCommerce plugin was disabled.

> PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class ‘WC_Calypso_Bridge_MailChimp_Settings_Controller’ does not have a method ‘get_store_info_schema’ in /opt/sites/1068962/wordpress/core/4.9/wp-includes/rest-api/class-wp-rest-server.php on line 1160

**Comment by iamgabrielma** [comment] 2017-11-29 07:07
Another case, this time with WooCommerce enabled:

<img width="1267" alt="screen shot 2017-11-29 at 14 04 34" src="https://user-images.githubusercontent.com/3812076/33362275-46f72994-d50e-11e7-8532-612cff069a55.png">

Chat 1156093-hc

**Comment by carladoria** [comment] 2018-01-07 11:30
also reported here [575419-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=575419)

**Comment by joshuatf** [comment] 2018-10-24 17:40
@justinshreve Did the latest rebase that removed `inc/wc-calypso-bridge-mailchimp-add-settings-error.php` resolve this issue?

**Comment by justinshreve** [comment] 2018-10-24 18:50
It looks like we are still using some Mailchimp API endpoints https://github.com/Automattic/wc-calypso-bridge/blob/master/store-on-wpcom/api/class-wc-calypso-bridge-mailchimp-settings-controller.php, so this issue might still be a problem.  I didn't see the warning earlier when disabling WC, but I didn't do much digging.

**Comment by timmyc** [comment] 2018-11-07 16:35
After chatting about this yesterday, I confirmed is indeed still being consumed in the email settings tab so we can't remove the code yet. But I did just run `wp plugin list` with calypso-bridge installed under multiple scenarios:

- woocommerce disabled
- woocommerce enabled, woo mailchimp disabled
- woocommerce enabled, woo mailchimp enabled

And I wasn't able to reproduce the error message anymore so I'm going to close this one out.

**Closed by timmyc** 2018-11-07 16:35 UTC
