### ISSUE TITLE
Dropdowns are disabled in tax settings

### ISSUE THREAD

**Issue by elizaan36** [Automattic/wc-calypso-bridge#746] opened 2021-09-09 18:58 UTC
After looking through some of the customer effort score feedback, I investigated an issue that kept coming up. It seems like some of the dropdowns are disabled in Settings > Tax for Ecom plan stores. This happens whether the new nav is disabled or not.

<img width="1021" alt="Screen Shot 2021-09-09 at 1 51 15 PM" src="https://user-images.githubusercontent.com/5121465/132746432-a7bccfd2-3679-4e88-827d-10d9d359dd59.png">

**Comment by mattsherman** [comment] 2021-09-16 18:38
@elizaan36 I think this is by design, and due to the WooCommerce Shipping and Tax extension.

With automated taxes disabled:

<img width="1266" alt="Screen Shot 2021-09-16 at 14 34 38" src="https://user-images.githubusercontent.com/2098816/133666519-99104310-71ad-4db5-8b4d-d5867185a56b.png">

With automated taxes enabled:

<img width="1266" alt="Screen Shot 2021-09-16 at 14 34 26" src="https://user-images.githubusercontent.com/2098816/133666564-78bcb809-a295-4a8f-a1cb-7bde4717ab51.png">

Now, one oddity is that your setup references "WooCommerce Services" under the automated taxes dropdown, whereas mine references "WooCommerce Tax". My understanding is that at some point in the past "WooCommerce Services" was renamed to "WooCommerce Shipping and Tax". Do you perhaps have an older version of that extension installed?

**Comment by elizaan36** [comment] 2021-09-16 20:42
Ah, you're right. This is a design issue. I'm going to keep this issue open for myself to come back to.😅

The name thing is strange though - the plugin should be up to date with `Version 1.25.18` and says "WooCommerce Shipping & Tax" in the plugins folder of this site.

**Comment by mattsherman** [comment] 2021-09-17 18:52
> Ah, you're right. This is a design issue. I'm going to keep this issue open for myself to come back to.😅

I'll assign this one to you for now, to note that. Though, perhaps we should move this issue to the [`Automattic/woocommerce-services` repo](https://github.com/Automattic/woocommerce-services)? 

> The name thing is strange though - the plugin should be up to date with `Version 1.25.18` and says "WooCommerce Shipping & Tax" in the plugins folder of this site.

Odd. That's the same version of the plugin I'm using. Again, perhaps it would be good for you to open up an issue in the `woocommerce-services` repo about this, as it seems directly related to that extension?

**Comment by warrendholmes** [comment] 2023-05-31 02:52
Closing these old issues out.

**Closed by warrendholmes** 2023-05-31 02:52 UTC
Labels: bug, [Status] Needs Author Reply, Needs design
