### ISSUE TITLE
Vertical Scrollbar Shown in New Navigation Sidebar

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#678] opened 2021-04-21 18:25 UTC
I tested this out on a new JN site running 5.2 and 2.2 of wc-admin, and I could not reproduce the bug there, so wondering if this is something specific to code here in the bridge.

__Steps to Recreate__
- Be sure to have scrollbars set to always display ( Settings > General on a mac )
![image](https://user-images.githubusercontent.com/22080/115602513-e329ed00-a293-11eb-97f3-d7a6881395ed.png)

- Then on an ecommerce plan site, navigate to the Woo Home Screen
- Note the vertical scrollbar that is shown

__eCom Home Screen__
![image](https://user-images.githubusercontent.com/22080/115602666-0785c980-a294-11eb-8ea3-00d816b566de.png)

__JN Woo 5.2.2 / WCA 2.2.1_
![image](https://user-images.githubusercontent.com/22080/115602788-30a65a00-a294-11eb-8db7-a225e5ded650.png)

**Comment by mattsherman** [comment] 2021-11-15 20:27
I'm not really sure that this was ever an issue. The screenshot of the "issue" on an eComm site appears to show a sidebar that *should* have a scrollbar, since it is taller than the available vertical space.

I have attempted to reproduce this on an eComm site, and the scrollbars appear and disappear as appropriate.

Closing this.

**Closed by mattsherman** 2021-11-15 20:27 UTC
Labels: bug
