### ISSUE TITLE
Create menu items for Shop/Cart/Checkout

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wc-calypso-bridge#960] opened 2023-02-16 11:39 UTC
The menu doesn’t have cart/checkout/shop pages

![image](https://user-images.githubusercontent.com/2484390/219354883-320d5d9e-29cf-4fc9-bd20-0ac346deb33c.png)

### Possible solution

It seems like there is a post in the posts table that holds the navigation

post type: wp_navigation
post_title: primary

We could check if those shop/cart/checkout pages exist, and if not append something like 

```
<!-- wp:navigation-link {"label":"Checkout","type":"page","id":773,"url":"https://devpanos.wpcomstaging.com/checkout/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Shop","type":"page","id":769,"url":"https://devpanos.wpcomstaging.com/shop/","kind":"post-type","isTopLevelLink":true} /-->
```

I did a quick test with PHPMyAdmin and it works - BUT I need to  `wp cache flush`

If there is a better (non hacky way) would be great

cc @daledupreez @xristos3490

**Comment by xristos3490** [comment] 2023-02-16 11:46
> It seems like there is a post in the posts table that holds the navigation

Great! Then we need to develop a filter function that replaces this value as part of our ecom provision/setup. 

> If there is a better (non hacky way) would be great

Not sure. I like the idea of having this fixed in a one-time operation in The Bridge. Perhaps the cache-flushing you experienced was caused by directly accessing the DB. If we go with the `WP_Post` API, it should be good, right?

**Comment by PanosSynetos** [comment] 2023-02-16 11:49
> I like the idea of having this fixed in a one-time operation in The Bridge

Yes, the same process that creates the missing ecomm pages, can also create the menu items

> caused by directly accessing the DB

Most def!

**Comment by xristos3490** [comment] 2023-02-16 12:03
> Yes, the same process that creates the missing ecomm pages, can also create the menu items

Exactly! We don't want to mess with existing navigations, only new ones!

**Closed** 2023-03-02 11:13 UTC
