### ISSUE TITLE
Change "Welcome to site title" to "Welcome to your Woo Express store"

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wc-calypso-bridge#1069] opened 2023-04-07 15:41 UTC
When Nux data is missing, we show a "Welcome to site title" above the task list. Newest design iterations show it defaulting to "Welcome to your Woo Express store."
https://www.figma.com/file/lD0gTB4IqGsmSmsnjZNaP6?node-id=2157:27769#385425873

**Comment by ilyasfoo** [comment] 2023-04-28 13:26
This is duplicate of https://github.com/Automattic/wp-calypso/issues/74898, and is already resolved by https://github.com/Automattic/wc-calypso-bridge/pull/1071. Closing

**Closed by ilyasfoo** 2023-04-28 13:26 UTC
Labels: Woo Express
