### ISSUE TITLE
AutomateWoo package issue

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1233] opened 2023-07-24 04:14 UTC
If I understand this problem from Slack p1689831468376719-slack-C03Q87XT1QF we may need to ensure that all Woo Express performance and ecommerce plan users do in fact have AutomateWoo installed and activated.

@andres-blanco Do we need to run an update script for existing stores?

**Comment by daledupreez** [comment] 2023-07-24 07:52
@warrendholmes, I believe an update needs to be run for existing stores to ensure that the WooCommerce.com subscriptions include AutomateWoo. That's a slightly different issue from ensuring that AutomateWoo is installed and activated.

It looks like our last set of changes in this area was in March 2023 as part of the refactoring/prep for the Woo Express Essential plan - you can see the last change here: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Sjbn%2Qrpbzzrepr%2Qfbsgjner.cuc%3Sn%3Qgehr%26e%3Q6r738r88%23133%2Q136-og

As importantly, you can see that we don't have a `'wccom-slug'` array key, which means we haven't been registering AutomateWoo with WooCommerce.com. However, it looks like this was only an issue for sites created after that refactor, as we were adding the slug in registrations that started after 2023-03-01 when we deployed D102721-code. However, it looks like we missed that addition in our refactoring.

**Comment by daledupreez** [comment] 2023-07-24 07:53
Fix for new registrations: D116734-code
Script we used for rolling out plugins and updating WooCommerce.com subs: fbhepr%2Skers%2Sjcpbz%2Sova%2Sbar%2Qgvzr%2S2023%2Shcqngr%2Qjbbpbzzrepr%2Qcyhtvaf.cuc%3Se%3Q27qo18n7-og

**Comment by warrendholmes** [comment] 2023-07-25 01:05
@daledupreez Sorry, I'm not quite following you there ... do we need to update the subs on WCCOM for the Performance plan? If so, who can help?

**Comment by daledupreez** [comment] 2023-07-25 10:39
We shipped the fix for new subscriptions yesterday in D116734-code just before 11:30am UTC yesterday.

However, the issue is that we've been installing the plugin, but not including the plugin in the list of plugins we register with WooCommerce.com.

At some point, we should run through the active sites with the Performance plan to update the WooCommerce.com registrations to include AutomateWoo. We may also need to fix current trial sites that upgrade to a Performance plan. This doesn't directly impact any in-product functionality, and I am not sure how many sites it affects, both of which would affect the prioritisation for fixing this up.

**Comment by warrendholmes** [comment] 2023-07-26 02:12
THANK YOU @daledupreez ... I don't think it's high priority if the experience for merchants is working as intended. The only thing I can think of that is important is that this would affect accounting for rev-share purposes, but given how few subscribers we have it wouldn't be much.

**Comment by daledupreez** [comment] 2023-07-26 06:34
As a further clarification, I don't believe this will impact how accounting is computed for revenue share purposes -- as far as I know, that logic is driven by which plugins are installed on the site.

**Comment by warrendholmes** [comment] 2023-07-26 06:50
Ok, in that case ... should we just close this out?

**Comment by daledupreez** [comment] 2023-08-10 08:41
Closing this as a wont-fix. We can revisit it if needed.

**Closed by daledupreez** 2023-08-10 08:41 UTC
