### ISSUE TITLE
Accessing product add-ons screens hides WooCommerce navigation

### ISSUE THREAD

**Issue by josemarques** [Automattic/wc-calypso-bridge#120] opened 2018-10-31 11:52 UTC
When accessing a Product add-ons screen the navigation hides the WooCommerce menus:

![poa](https://user-images.githubusercontent.com/57050/47786354-73120000-dd03-11e8-8eb2-b958b03b1703.gif)

**Comment by justinshreve** [comment] 2018-10-31 11:53
Duplicate of https://github.com/Automattic/wc-calypso-bridge/issues/87. I'll fix shortly!

**Closed by justinshreve** 2018-10-31 11:53 UTC
Labels: eCommerce Plan
